defaults:
  - _self_

meta:
  experiment_pack: AugC-INR3

  run_name:  null
  seed:      42

inference:
  ckpt: save_models/inr/vanilla/sneaky-stag-351_20260313_1714_best.pt
  #save_models/inr/INR_LSTM_FREEZE/delightful-stag-610_20260316_1057_best.pt

  # VANILLA - save_models/inr/vanilla/sneaky-stag-351_20260313_1714_best.pt

  # FREEZE - save_models/inr/INR_LSTM_FREEZE/delicate-panda-635_20260316_1057_best.pt
  # NON FREEZE - save_models/inr/INR_LSTM_FREEZE/delightful-stag-610_20260316_1057_best.pt

  #null   # null = dernier _best.pt  |  "save_models/inr/run_xxx_best.pt"
  n_plots: 8


paths:
  save_models:  save_models/inr2/
  scalers_file: save_models/inr/INR_LSTM_FREEZE/scalers.pkl

data:
  train_parquet:    data/train_data.parquet
  val_parquet:      data/val_data.parquet
  test_parquet:     data/test_data.parquet
  dataset_name:     nz
  input_dim:        1      # dimension coords temporelles ?
  output_dim:       1       # flow
  look_back_window: 192     # heures observation (serie_p)
  horizon:          48     # heures prédiction  (serie_h)
  num_workers:      1
  pin_memory:       true

inr:
  control:              "dynamic"
  use_context:          true
  use_static_context:   true    # ← ablation : features géo-statiques
  use_dynamic_context:  true    # ← ablation : features temporelles (x_time)
  freeze_lstm:          false

  lstm_ckpt:        null #save_models/head_lstm/debonair-wolf-926_h256_20260316_1006_best.pt # null    # "save_models/head_lstm/run_xxx_best.pt" ou null
  lstm_hidden_dim:  256
  latent_dim:       256 # DIM CODE #512
  hidden_dim:       128 # WIDTH INR
  depth: 4

  num_frequencies:  8
  min_frequencies:  0
  base_frequency:   1.25
  include_input:    false
  static:
    spatial_dim:    128      # sortie FourierSpatialEncoder
    dir_dim:        8 #8       # sortie nn.Embedding direction
    num_directions: 7       # nb directions distinctes
    sigma:          0.1     # échelle Fourier (0.1 = sensible grandes distances)

optim:
  lr_inr:           1.0e-4
  lr_code:          1.0e-2
  weight_decay:     1.0e-5
  batch_size:       32
  epochs:           100
  scheduler:        cosine  # cosine | null
  t_max:            200
  clip_grad_value:  1.0

inner:
  inner_steps:      3
  w_passed:         1.0
  w_futur:          1.0

misc:
  log_every_n_epochs:  10
  save_every_n_epochs: 10
  version:             1